### ISSUE TITLE
[REQ] Support for message translation

### ISSUE THREAD

**Issue by crashzk** [ManifestManah/MetaCommandsBlocker#1]
It would be possible? Or do we need to wait for a CSSharp release with this support for this?

**Comment by ManifestManah** [comment]
Sorry for the delayed response, I've first gotten around to addressing some of my plugins' issues now due to being quite busy as of late. To answer your question; yes, I will be awaiting the release of a standardized translation system by CounterStrikeSharp before implementing this feature, albeit when time comes it will be added.

**Comment by crashzk** [comment]
@ManifestManah would it be possible to now support message translation?
